### ISSUE TITLE
Implement JSX transpilation

### ISSUE THREAD

**Issue by elevatebart** [vue-styleguidist/vue-live#12]
Using acorn-jsx, I believe I can extract JSX in an optimized manner and might be able to use vue-babel-transform to fix-up the details.
In order to keep it light, I might make it an option.

**Comment by elevatebart** [comment]
@Aaron-Pool you have been tagged ;)
Thank you so much

**Comment by elevatebart** [comment]
You might have conflicts with the weird hybrid mode.
Where JS and template are not split normally (that looks a lot like jsx)

```js
// the js
var today = New Date()

// then the template detected by a line starting with "<"
<input type="date" :value="today">
```

**Comment by Aaron-Pool** [comment]
Thanks! If I don't follow up in this at some point over the next few days, feel free to ping me again. I probably just forgot!

**Comment by Aaron-Pool** [comment]
@elevatebart 

Ok update: I pulled the repo down and dug around for a few hours last night. Even started to work on the implementation, but there's one pretty substantial issue we're going to run into:  Babel doesn't use a pure `AST` tree. They use  an augmented `AST` tree that has the basic unit `path` instead of `node`. The `path` is essentially a traditional `node` augmented with a bunch of meta data and helper functions.  And unfortunately, that `path` is what babel plugins consume. And therefor also what the `babel-plugin-vue-jsx-transform` expects to receive.

Because of that, I can't just add a visitor for `JSXElement` types to your `walkes` traversal. Because, `walkes` only provides standard `AST` nodes. 

Anyways, it's not necessarily a difficult problem to solve, it's simple to bring in Babel's `traversal` utility instead of `walkes`. It is, however, _substantially_ larger. So the real issue is going to be an increase in package size. Maybe rollup can do some magic to remove unused code, but I doesn't seem like devs who write build tools work quite as hard at making their libraries treeshakable as front end developers do. Prime example: the index file of `@babel/traverse` imports `*` from `@babel/types` (which by itself is 228kb 😦 ).

Gonna keep digging around later, see if I can find anything lighter, considering the limited subset of Babel that we need to transpile the JSX.

**Comment by elevatebart** [comment]
Done in v1.3

**Comment by Aaron-Pool** [comment]
Great job! @elevatebart
