### ISSUE TITLE
Error parsing components with lists

### ISSUE THREAD

**Issue by justin-schroeder** [vue-styleguidist/vue-live#41]
Howdy @elevatebart 👋,

Got a new one for you that seems to have been introduced in `1.9+`. We've done a fair amount of sleuthing on it and have a good reproduction which explains the issue, but the crux of it is, any components with lists cause a bunch of errors. We've walked up and down the version tree and isolated it to 1.9. 1.9.1 gives a somewhat more helpful error message (again detailed on the reproduction).

We have a suspicion it has to do with parsing out the commas but aren't deep enough into this project to know if that's accurate or not. Here's a reproduction repository:

https://github.com/wearebraid/vuepress-vuelive-no-ssr-bug

And here is a live version of the reproduction:

https://vuepress-vuelive-no-ssr-bug.vercel.app/

Thanks!

**Comment by elevatebart** [comment]
Hey justin, it seems you found yet another bug in the `vue-inbrowser-compile`

**Comment by elevatebart** [comment]
The problem is here:
https://github.com/vue-styleguidist/vue-live/blob/25c2e391f781f7c248e576c7b413a81a693a846a/src/utils/checkTemplate.js#L57

In order to accept arrays in the parse, I make it incompatible with object litterals:

The espression `{key:'33'}` turns into `() => {{key:'33'}}` that does not parse.
To fix it, the best way would probably be to wrap our expresssions in a real function instead of an arrow function yielding `function() {return {key:'33'}}`. What if we have multiple lines in this expression...
